### ISSUE TITLE
Investigate tests failing between python versions

### ISSUE THREAD

**Issue by olivialynn** [LSSTDESC/rail_cmnn#10]
Seen in #9

This is a problem on other rail repos:
(to add)

**Comment by sschmidt23** [comment]
As I think I mentioned in the telecon, I think the test in #9 is failing because hdf5_groupname got added to the list of SHARED_PARAMS in the CatEstimator parent class for all of the estimators ([L30 of estimator.py in rail_base](https://github.com/LSSTDESC/rail_base/blob/cccd4c8aa8a561236f8adfaa7ec863dc8a7bfde4/src/rail/estimation/estimator.py#L30)).  So, the test `test_missing_groupname` that used to test for hdf5_groupname being missing, no longer fails as it did before that SHARED_PARAMS default was added (test is [here](https://github.com/LSSTDESC/rail_cmnn/blob/a64902b2c962e2382bec5df29e3ba407b08be4cc/tests/test_algos.py#L61)).  We can either change the test to be looking for the incorrect group-name and feed it a bad group-name in the param dict, or just delete the test, as it looks like there is already a #pragma no cover for the hdf5_groupname not being present anyway.

And I don't think it has anything to do with the python version, it should fail for all versions of python if the error is being caused by what I think it is.
